#include <iostream>
#include <string>
#include <cstdlib>
#include <ctime>

using namespace std;

int main()
{
	int num; // holding a random number generated by computer
	int guess; // holds the guess of the user
	int highscore = 7;
	bool isGuessed = false; // true if user guessed the number correctly
	string choice = "yes";
	int count = 0; // how many times the user guessing the number

	srand(time(0)); // initialize randomness with time
	num = rand() % 100; // ensure the number is 0 to 100

	cout << "I have a number between 0 and 100. Try to guess what it is." << endl << endl;
	choice = "yes";

	while (choice == "yes")
	{
		if (choice == "yes")
			isGuessed = false;
		    count = 0;

		while (!isGuessed)
		{
			count++;

			if (count > 6)
			{
				cout << "You lost the game!" << endl;
				break;
			}

			else if (count <= 6)
			{
				cout << "So, what is your guess? ";
				cin >> guess;

				if (guess == num)
				{
					cout << "You got it in " << count << " times!" << endl;
					isGuessed = true;

					if (highscore > count)
						highscore = count;

					cout << "The highest score is " << highscore << endl;
				}

				else if (guess < num)
				{
					if (num > guess + 50)
						cout << "Your guess is way too low." << endl;

					else if (num < guess + 15)
						cout << "Your answer is a little bit low." << endl;

					else
						cout << "Your guess is too low, go higher!" << endl;
				}

				else if (guess > num)
				{
					if (num < guess - 50)
						cout << "Your guess is way too high." << endl;

					else if (num > guess - 50)
						cout << "Your answer is a little bit high." << endl;

					else
						cout << "Your guess is too high, go higher!" << endl;
				}
			}

		}

		cout << "Do you want to play again? (yes/no) ";
		cin >> choice;
	}

	system("PAUSE");
	return 0;
}